#!/bin/bash

# Copyright (C) 2012 Adam Monsen <haircut@gmail.com>
# License: MIT License (same as Symfony2 itself). See end of script for more
# license information.

# For 1 to n directories with git clones, commit.

# Usage: multicommit CLONE [CLONE...]
# Example: multigit UserBundle TestUtilBundle

set -o errexit
trap 'rm $commit_message_file' EXIT

commit_message_file=`mktemp`
echo > $commit_message_file
cat >> $commit_message_file <<EndOfCommitMessageHeader
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
EndOfCommitMessageHeader
multidiff "$@" >> $commit_message_file
vim +0 -c 'set ft=gitcommit' $commit_message_file
sed -i '/^#/,$d' $commit_message_file

origdir=`pwd`
for clone in "$@"
do
    builtin cd "$clone"

    if git status --porcelain | grep -q .
    then
        git commit -a -F $commit_message_file
    fi

    builtin cd "$origdir"
done

# "MIT" (Expat) license:
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
