#!/bin/bash

# Copyright (C) 2012 Adam Monsen <haircut@gmail.com>
# License: MIT License. See end of script for more license information.

# For 1 to n directories with git clones, look for uncommitted and/or unpushed
# changes.

# Usage: multistatus UserBundle TestUtilBundle

verbose=false
if [[ "$1" == "-v" ]]
then
    verbose=true
    shift
fi

for clone in "$@"
do
    origdir=`pwd`
    builtin cd "$clone"
    status=`git status`
    diverged=`grep -i 'have diverged' <<< $status`
    outofsync=`grep -i 'your branch is' <<< $status`
    unstaged=`grep -i 'changes not staged' <<< $status`
    untracked=`grep -i 'untracked file' <<< $status`
    uncommitted=`grep -i 'changes to be' <<< $status`

    if [[ $verbose == true && ( -n "$diverged" || -n "$outofsync" || -n "$unstaged" || -n "$untracked" || -n "$uncommitted") ]]
    then
        echo "# MULTISTATUS - $clone"
        git status
    else
        if [[ -n "$diverged" || -n "$outofsync" || -n "$unstaged" || -n "$untracked" || -n "$uncommitted" ]]
        then
            echo $clone
        fi
    fi

    builtin cd "$origdir"
done

# "MIT" (Expat) license:
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
