#!/bin/bash

# Copyright (C) 2012 Adam Monsen <haircut@gmail.com>
# License: MIT License. See end of script for more license information.

# For 1 to n directories with git clones, "git pull --rebase".
# Bail out if rebase cannot be automatically completed.

# Usage: multipullrebase UserBundle TestUtilBundle

origdir=`pwd`
for clone in "$@"
do
    echo `basename $clone`
    cd "$clone"

    git pull --rebase
    rv=$?
    [[ $rv -ne 0 ]] && exit $rv

    cd "$origdir"
done

# "MIT" (Expat) license:
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
